// 📚 Thư viện sách: danh sách sách và các bài. Nội dung từng bài: public/library/<sách>/<bài>.json
// (tạo bởi scripts/build-library.mjs từ data/library/<sách>/*.json — sổ tay học tự biên soạn, không chép nguyên văn sách)
export const LIBRARY = [
  {
    id: "it-c1",
    title: "ITの日本語 ソフトウェア開発プロジェクト",
    titleRo: "IT no Nihongo: Sofutowea kaihatsu purojekuto",
    vi: "Tiếng Nhật Công nghệ Thông tin trong ngành phần mềm",
    sub: "ソフトウェア開発プロジェクト",
    level: "Trung cấp · N3–N2",
    authors: "Đặng Khải Hoàn, Đinh Thị Hằng Nga, Nguyễn Anh Vũ, Nguyễn Thị Khánh, Nguyễn Thị Cẩm Lý, Komaki Michiko",
    publisher: "NXB Thế Giới · Thaihabooks · FPT Software",
    color: "80,130,220",
    cover: { badge: "PJ", sub: "開発プロジェクト", c1: "#2c4a86", c2: "#1b2f5c" },
    lessonsHead: "15 bài theo vòng đời dự án",
    lessonsSub: "Từ khái quát dự án, báo giá, thiết kế, kiểm thử đến khảo sát khách hàng",
    patternsSub: "Mẫu câu đánh số trong hội thoại mẫu của sách",
    lessonLabel: "レッスン",
    desc: "15 bài đi trọn một dự án phần mềm waterfall (dự án SuperTrans): kiến thức IT, thuật ngữ và hội thoại họp với khách Nhật.",
    lessons: [
      { n: 1, page: 21, jp: "プロジェクト概要", ro: "Purojekuto gaiyoo", vi: "Khái quát dự án" },
      { n: 2, page: 31, jp: "見積り", ro: "Mitsumori", vi: "Ước tính / báo giá" },
      { n: 3, page: 41, jp: "開発環境", ro: "Kaihatsu kankyoo", vi: "Môi trường phát triển" },
      { n: 4, page: 51, jp: "議事録", ro: "Gijiroku", vi: "Biên bản họp" },
      { n: 5, page: 61, jp: "要件定義", ro: "Yooken teigi", vi: "Định nghĩa yêu cầu" },
      { n: 6, page: 71, jp: "基本設計", ro: "Kihon sekkei", vi: "Thiết kế cơ bản" },
      { n: 7, page: 81, jp: "要求変更", ro: "Yookyuu henkoo", vi: "Thay đổi yêu cầu" },
      { n: 8, page: 91, jp: "詳細設計", ro: "Shoosai sekkei", vi: "Thiết kế chi tiết" },
      { n: 9, page: 101, jp: "週報", ro: "Shuuhoo", vi: "Báo cáo tuần" },
      { n: 10, page: 111, jp: "情報セキュリティ", ro: "Joohoo sekyuriti", vi: "Bảo mật thông tin" },
      { n: 11, page: 121, jp: "コーディング規約", ro: "Koodingu kiyaku", vi: "Quy ước lập trình" },
      { n: 12, page: 133, jp: "ソフトウェアテスト", ro: "Sofutowea tesuto", vi: "Kiểm thử phần mềm" },
      { n: 13, page: 145, jp: "品質報告", ro: "Hinshitsu hookoku", vi: "Báo cáo chất lượng" },
      { n: 14, page: 157, jp: "リリースノート", ro: "Ririisu nooto", vi: "Release note" },
      { n: 15, page: 167, jp: "お客様アンケート", ro: "Okyakusama ankeeto", vi: "Khảo sát khách hàng" },
    ],
    extras: [
      { id: "nhan-vat", ico: "👥", jp: "主な登場人物", vi: "Nhân vật & dự án SuperTrans" },
      { id: "viet-tat", ico: "🔤", jp: "略語一覧", vi: "Từ viết tắt IT" },
      { id: "ky-hieu", ico: "#️⃣", jp: "記号一覧", vi: "Cách đọc ký hiệu" },
      { id: "tu-vung", ico: "🔎", jp: "用語索引", vi: "Tra cứu toàn bộ từ vựng" },
    ],
  },
  {
    id: "it-b2",
    title: "ITの日本語 B2 会話編",
    titleRo: "IT no Nihongo B2 Kaiwa-hen",
    vi: "Tiếng Nhật Công nghệ Thông tin – Hội thoại trong dự án phần mềm",
    sub: "ソフトウェア開発プロジェクト",
    level: "B2 · ~N3",
    authors: "Komaki Michiko, Nguyễn Thị Khánh, Đặng Khải Hoàn, Đinh Thị Hằng Nga, Nguyễn Thị Cẩm Lý, Nguyễn Anh Vũ",
    publisher: "NXB Thế Giới · Thaihabooks",
    color: "64,160,90",
    cover: { badge: "B2", sub: "会話編", c1: "#3f9a58", c2: "#2b7442" },
    lessonsHead: "15 bài hội thoại",
    lessonsSub: "Theo tiến trình một dự án phần mềm",
    patternsSub: "Mẫu gạch chân trong hội thoại của sách",
    desc: "15 tình huống hội thoại trong một dự án phần mềm Nhật – Việt, từ buổi gặp đầu tiên đến khi kết thúc onsite.",
    lessons: [
      { n: 1, page: 31, jp: "初回訪問のあいさつ", ro: "Shokai hoomon no aisatsu", vi: "Chào hỏi trong lần gặp đầu tiên" },
      { n: 2, page: 41, jp: "キックオフミーティング プロジェクトの目的と概要", ro: "Kikkuofu miitingu: purojekuto no mokuteki to gaiyoo", vi: "Họp khởi động: mục đích và tổng quan dự án" },
      { n: 3, page: 51, jp: "キックオフミーティング スケジュールと進め方", ro: "Kikkuofu miitingu: sukejuuru to susumekata", vi: "Họp khởi động: lịch trình và cách triển khai" },
      { n: 4, page: 61, jp: "キックオフミーティング プロジェクト体制の説明", ro: "Kikkuofu miitingu: purojekuto taisei no setsumei", vi: "Họp khởi động: giới thiệu cơ cấu nhân sự dự án" },
      { n: 5, page: 71, jp: "オンサイト初日のあいさつ", ro: "Onsaito shonichi no aisatsu", vi: "Chào hỏi ngày đầu onsite" },
      { n: 6, page: 81, jp: "お客様の会社のルール", ro: "Okyakusama no kaisha no ruuru", vi: "Quy định ở công ty khách hàng" },
      { n: 7, page: 91, jp: "要件の説明", ro: "Yooken no setsumei", vi: "Giải thích yêu cầu" },
      { n: 8, page: 101, jp: "定例会議 進捗の報告", ro: "Teirei kaigi: shinchoku no hookoku", vi: "Họp định kỳ: báo cáo tiến độ" },
      { n: 9, page: 111, jp: "定例会議 課題の報告", ro: "Teirei kaigi: kadai no hookoku", vi: "Họp định kỳ: báo cáo vấn đề" },
      { n: 10, page: 121, jp: "定例会議 Q&Aの確認", ro: "Teirei kaigi: Q&A no kakunin", vi: "Họp định kỳ: xác nhận Q&A" },
      { n: 11, page: 131, jp: "製品デモ", ro: "Seihin demo", vi: "Demo sản phẩm" },
      { n: 12, page: 141, jp: "課題解決の相談", ro: "Kadai kaiketsu no soodan", vi: "Bàn cách giải quyết vấn đề" },
      { n: 13, page: 151, jp: "納品とリリースノート", ro: "Noohin toririisu nooto", vi: "Bàn giao sản phẩm và release note" },
      { n: 14, page: 161, jp: "UATサポートタスクの確認", ro: "UAT sapooto tasuku no kakunin", vi: "Xác nhận công việc hỗ trợ UAT" },
      { n: 15, page: 171, jp: "オンサイト終了のあいさつ", ro: "Onsaito shuuryoo no aisatsu", vi: "Chào hỏi khi kết thúc onsite" },
    ],
    // phần tra cứu thêm (không theo bài)
    extras: [
      { id: "nhan-vat", ico: "👥", jp: "主な登場人物", vi: "Nhân vật trong sách" },
      { id: "kinh-ngu", ico: "🙇", jp: "敬語のまとめ", vi: "Tóm tắt kính ngữ" },
      { id: "viet-tat", ico: "🔤", jp: "略語一覧", vi: "Từ viết tắt IT" },
      { id: "tu-vung", ico: "🔎", jp: "用語索引", vi: "Tra cứu toàn bộ từ vựng" },
    ],
  },
];

export const bookById = (id) => LIBRARY.find((b) => b.id === id);
export const lessonUrl = (book, n) => `/library/${book}/${n}.json`;
export const lessonName = (B, n) => (B?.lessonLabel ? `${B.lessonLabel}${n}` : `第${n}課`);
