// 📚 Thư viện sách: danh sách sách và các bài. Nội dung từng bài: public/library/<sách>/<bài>.json
// (tạo bởi scripts/build-library.mjs từ data/library/<sách>/*.json — sổ tay học tự biên soạn, không chép nguyên văn sách)
// các khu sách (mỗi khu một trang riêng /thu-vien/<id>, không trùng id sách)
export const CATEGORIES = [
  { id: "it", ico: "💻", name: "Tiếng Nhật IT", jp: "ITの日本語", color: "80,130,220", sub: "Dự án phần mềm, họp với khách Nhật",
    desc: "Sách tiếng Nhật công nghệ thông tin: hội thoại trong dự án phần mềm, thuật ngữ IT, kính ngữ công sở." },
  { id: "dieu-duong", ico: "🩺", name: "Tiếng Nhật Điều dưỡng", jp: "介護の日本語", color: "235,120,70", sub: "Chăm sóc người cao tuổi (介護)",
    desc: "Sách tiếng Nhật cho công việc điều dưỡng – chăm sóc (介護): câu nói với người được chăm sóc, từ vựng cơ thể, bệnh, dụng cụ và kỹ năng chăm sóc." },
];
export const catById = (id) => CATEGORIES.find((c) => c.id === id);
export const booksIn = (cat) => LIBRARY.filter((b) => (b.cat || "it") === cat);

export const LIBRARY = [
  {
    id: "kaigo-1",
    cat: "dieu-duong",
    title: "やさしい日本語とイラストでわかる 介護のしごと",
    titleRo: "Yasashii nihongo to irasuto de wakaru: Kaigo no shigoto",
    vi: "Công việc chăm sóc – điều dưỡng (介護) qua tiếng Nhật dễ hiểu và tranh minh họa",
    sub: "介護職員初任者研修 学習者向け",
    level: "Khóa 初任者研修 · ~N4–N3",
    authors: "Hori Hisano (堀永乃) biên soạn",
    publisher: "日本医療企画 (JMP)",
    color: "235,130,90",
    cover: { top: "介護", mid: "のしごと", badge: "やさしい", sub: "初任者研修", c1: "#f0a35e", c2: "#d9703a" },
    lessonsHead: "18 bài chăm sóc theo chủ đề",
    lessonsSub: "Gộp từ 49 bài ngắn của sách: kiến thức nền, chăm sóc người sa sút trí tuệ, ăn uống, tắm, bài tiết, di chuyển…",
    patternsSub: "Câu nói thực tế với người được chăm sóc và đồng nghiệp",
    lessonLabel: "テーマ",
    sceneHead: "📘 Nội dung tương ứng trong sách",
    termsHead: "🔑 Thuật ngữ chăm sóc – y tế",
    tipsHead: "💡 Mẹo khi làm việc chăm sóc",
    desc: "Kiến thức khóa 介護職員初任者研修 bằng tiếng Nhật dễ, kèm câu nói thực tế khi chăm sóc người cao tuổi, từ vựng cơ thể, bệnh, dụng cụ.",
    lessons: [
      { n: 1, page: 10, jp: "介護の仕事と人権", ro: "Kaigo no shigoto to jinken", vi: "Nghề chăm sóc, nhân quyền, QOL, bình thường hóa" },
      { n: 2, page: 14, jp: "自立支援と職業倫理", ro: "Jiritsu shien to shokugyoo rinri", vi: "Hỗ trợ tự lập, nguyên tắc thực hành, đạo đức nghề" },
      { n: 3, page: 20, jp: "介護事故の予防とこころの健康", ro: "Kaigo jiko no yoboo to kokoro no kenkoo", vi: "Phòng ngừa tai nạn & sức khỏe tinh thần" },
      { n: 4, page: 24, jp: "介護保険制度と介護サービス", ro: "Kaigo hoken seido to kaigo saabisu", vi: "Bảo hiểm chăm sóc & các loại dịch vụ" },
      { n: 5, page: 34, jp: "介護職と医行為・個人の権利", ro: "Kaigoshoku to ikooi, kojin no kenri", vi: "Hành vi y tế & bảo vệ quyền cá nhân" },
      { n: 6, page: 40, jp: "介護のコミュニケーション", ro: "Kaigo no komyunikeeshon", vi: "Giao tiếp trong chăm sóc" },
      { n: 7, page: 44, jp: "介護記録とホウレンソウ", ro: "Kaigo kiroku to hoorensoo", vi: "Ghi chép chăm sóc, báo cáo – liên lạc – xin ý kiến" },
      { n: 8, page: 46, jp: "老化と高齢者に多い病気", ro: "Rooka to kooreisha ni ooi byooki", vi: "Lão hóa & bệnh thường gặp ở người cao tuổi" },
      { n: 9, page: 50, jp: "認知症の原因と症状", ro: "Ninchishoo no gen'in to shoojoo", vi: "Sa sút trí tuệ: nguyên nhân & triệu chứng" },
      { n: 10, page: 54, jp: "認知症ケアと家族支援", ro: "Ninchishoo kea to kazoku shien", vi: "Chăm sóc người sa sút trí tuệ & hỗ trợ gia đình" },
      { n: 11, page: 58, jp: "障害の理解", ro: "Shoogai no rikai", vi: "Hiểu về khuyết tật" },
      { n: 12, page: 66, jp: "記憶と脳", ro: "Kioku to noo", vi: "Trí nhớ & cấu tạo não" },
      { n: 13, page: 70, jp: "家事支援と居住環境", ro: "Kaji shien to kyojuu kankyoo", vi: "Hỗ trợ việc nhà & môi trường sống an toàn" },
      { n: 14, page: 74, jp: "身じたく（衣服・着脱・口腔ケア）", ro: "Mijitaku (ifuku, chakudatsu, kookuu kea)", vi: "Quần áo, thay đồ & chăm sóc răng miệng" },
      { n: 15, page: 76, jp: "食事の介助", ro: "Shokuji no kaijo", vi: "Dinh dưỡng & hỗ trợ ăn uống" },
      { n: 16, page: 84, jp: "からだの動きと移動介助", ro: "Karada no ugoki to idoo kaijo", vi: "Tư thế, cơ học cơ thể, hỗ trợ đi lại & xe lăn" },
      { n: 17, page: 93, jp: "清潔と排泄の介助", ro: "Seiketsu to haisetsu no kaijo", vi: "Lau người, tắm & hỗ trợ bài tiết" },
      { n: 18, page: 100, jp: "睡眠・看取り・レクリエーション", ro: "Suimin, mitori, rekuriesshon", vi: "Giấc ngủ, chăm sóc cuối đời, sinh hoạt giải trí" },
    ],
    extras: [
      { id: "co-the", ico: "🧍", jp: "からだの部位の名称", vi: "Tên bộ phận cơ thể" },
      { id: "thuoc", ico: "💊", jp: "薬の種類と剤型", vi: "Các loại thuốc & cách đếm" },
      { id: "ghi-chep", ico: "📋", jp: "介護記録表の読み方", vi: "Đọc phiếu ghi chép chăm sóc" },
      { id: "xe-lan", ico: "♿", jp: "車いすの各部の名称", vi: "Bộ phận xe lăn" },
      { id: "phong-tuc", ico: "🎎", jp: "日本の行事・しきたり", vi: "Lễ hội, phong tục & lễ mừng thọ" },
      { id: "tu-vung", ico: "🔎", jp: "用語索引", vi: "Tra cứu toàn bộ từ vựng" },
    ],
  },
  {
    id: "it-c1",
    cat: "it",
    title: "ITの日本語 ソフトウェア開発プロジェクト",
    titleRo: "IT no Nihongo: Sofutowea kaihatsu purojekuto",
    vi: "Tiếng Nhật Công nghệ Thông tin trong ngành phần mềm",
    sub: "ソフトウェア開発プロジェクト",
    level: "Trung cấp · N3–N2",
    authors: "Đặng Khải Hoàn, Đinh Thị Hằng Nga, Nguyễn Anh Vũ, Nguyễn Thị Khánh, Nguyễn Thị Cẩm Lý, Komaki Michiko",
    publisher: "NXB Thế Giới · Thaihabooks · FPT Software",
    color: "80,130,220",
    cover: { badge: "PJ", sub: "開発プロジェクト", c1: "#2c4a86", c2: "#1b2f5c" },
    lessonsHead: "15 bài theo vòng đời dự án",
    lessonsSub: "Từ khái quát dự án, báo giá, thiết kế, kiểm thử đến khảo sát khách hàng",
    patternsSub: "Mẫu câu đánh số trong hội thoại mẫu của sách",
    lessonLabel: "レッスン",
    desc: "15 bài đi trọn một dự án phần mềm waterfall (dự án SuperTrans): kiến thức IT, thuật ngữ và hội thoại họp với khách Nhật.",
    lessons: [
      { n: 1, page: 21, jp: "プロジェクト概要", ro: "Purojekuto gaiyoo", vi: "Khái quát dự án" },
      { n: 2, page: 31, jp: "見積り", ro: "Mitsumori", vi: "Ước tính / báo giá" },
      { n: 3, page: 41, jp: "開発環境", ro: "Kaihatsu kankyoo", vi: "Môi trường phát triển" },
      { n: 4, page: 51, jp: "議事録", ro: "Gijiroku", vi: "Biên bản họp" },
      { n: 5, page: 61, jp: "要件定義", ro: "Yooken teigi", vi: "Định nghĩa yêu cầu" },
      { n: 6, page: 71, jp: "基本設計", ro: "Kihon sekkei", vi: "Thiết kế cơ bản" },
      { n: 7, page: 81, jp: "要求変更", ro: "Yookyuu henkoo", vi: "Thay đổi yêu cầu" },
      { n: 8, page: 91, jp: "詳細設計", ro: "Shoosai sekkei", vi: "Thiết kế chi tiết" },
      { n: 9, page: 101, jp: "週報", ro: "Shuuhoo", vi: "Báo cáo tuần" },
      { n: 10, page: 111, jp: "情報セキュリティ", ro: "Joohoo sekyuriti", vi: "Bảo mật thông tin" },
      { n: 11, page: 121, jp: "コーディング規約", ro: "Koodingu kiyaku", vi: "Quy ước lập trình" },
      { n: 12, page: 133, jp: "ソフトウェアテスト", ro: "Sofutowea tesuto", vi: "Kiểm thử phần mềm" },
      { n: 13, page: 145, jp: "品質報告", ro: "Hinshitsu hookoku", vi: "Báo cáo chất lượng" },
      { n: 14, page: 157, jp: "リリースノート", ro: "Ririisu nooto", vi: "Release note" },
      { n: 15, page: 167, jp: "お客様アンケート", ro: "Okyakusama ankeeto", vi: "Khảo sát khách hàng" },
    ],
    extras: [
      { id: "nhan-vat", ico: "👥", jp: "主な登場人物", vi: "Nhân vật & dự án SuperTrans" },
      { id: "viet-tat", ico: "🔤", jp: "略語一覧", vi: "Từ viết tắt IT" },
      { id: "ky-hieu", ico: "#️⃣", jp: "記号一覧", vi: "Cách đọc ký hiệu" },
      { id: "tu-vung", ico: "🔎", jp: "用語索引", vi: "Tra cứu toàn bộ từ vựng" },
    ],
  },
  {
    id: "it-b2",
    cat: "it",
    title: "ITの日本語 B2 会話編",
    titleRo: "IT no Nihongo B2 Kaiwa-hen",
    vi: "Tiếng Nhật Công nghệ Thông tin – Hội thoại trong dự án phần mềm",
    sub: "ソフトウェア開発プロジェクト",
    level: "B2 · ~N3",
    authors: "Komaki Michiko, Nguyễn Thị Khánh, Đặng Khải Hoàn, Đinh Thị Hằng Nga, Nguyễn Thị Cẩm Lý, Nguyễn Anh Vũ",
    publisher: "NXB Thế Giới · Thaihabooks",
    color: "64,160,90",
    cover: { badge: "B2", sub: "会話編", c1: "#3f9a58", c2: "#2b7442" },
    lessonsHead: "15 bài hội thoại",
    lessonsSub: "Theo tiến trình một dự án phần mềm",
    patternsSub: "Mẫu gạch chân trong hội thoại của sách",
    desc: "15 tình huống hội thoại trong một dự án phần mềm Nhật – Việt, từ buổi gặp đầu tiên đến khi kết thúc onsite.",
    lessons: [
      { n: 1, page: 31, jp: "初回訪問のあいさつ", ro: "Shokai hoomon no aisatsu", vi: "Chào hỏi trong lần gặp đầu tiên" },
      { n: 2, page: 41, jp: "キックオフミーティング プロジェクトの目的と概要", ro: "Kikkuofu miitingu: purojekuto no mokuteki to gaiyoo", vi: "Họp khởi động: mục đích và tổng quan dự án" },
      { n: 3, page: 51, jp: "キックオフミーティング スケジュールと進め方", ro: "Kikkuofu miitingu: sukejuuru to susumekata", vi: "Họp khởi động: lịch trình và cách triển khai" },
      { n: 4, page: 61, jp: "キックオフミーティング プロジェクト体制の説明", ro: "Kikkuofu miitingu: purojekuto taisei no setsumei", vi: "Họp khởi động: giới thiệu cơ cấu nhân sự dự án" },
      { n: 5, page: 71, jp: "オンサイト初日のあいさつ", ro: "Onsaito shonichi no aisatsu", vi: "Chào hỏi ngày đầu onsite" },
      { n: 6, page: 81, jp: "お客様の会社のルール", ro: "Okyakusama no kaisha no ruuru", vi: "Quy định ở công ty khách hàng" },
      { n: 7, page: 91, jp: "要件の説明", ro: "Yooken no setsumei", vi: "Giải thích yêu cầu" },
      { n: 8, page: 101, jp: "定例会議 進捗の報告", ro: "Teirei kaigi: shinchoku no hookoku", vi: "Họp định kỳ: báo cáo tiến độ" },
      { n: 9, page: 111, jp: "定例会議 課題の報告", ro: "Teirei kaigi: kadai no hookoku", vi: "Họp định kỳ: báo cáo vấn đề" },
      { n: 10, page: 121, jp: "定例会議 Q&Aの確認", ro: "Teirei kaigi: Q&A no kakunin", vi: "Họp định kỳ: xác nhận Q&A" },
      { n: 11, page: 131, jp: "製品デモ", ro: "Seihin demo", vi: "Demo sản phẩm" },
      { n: 12, page: 141, jp: "課題解決の相談", ro: "Kadai kaiketsu no soodan", vi: "Bàn cách giải quyết vấn đề" },
      { n: 13, page: 151, jp: "納品とリリースノート", ro: "Noohin toririisu nooto", vi: "Bàn giao sản phẩm và release note" },
      { n: 14, page: 161, jp: "UATサポートタスクの確認", ro: "UAT sapooto tasuku no kakunin", vi: "Xác nhận công việc hỗ trợ UAT" },
      { n: 15, page: 171, jp: "オンサイト終了のあいさつ", ro: "Onsaito shuuryoo no aisatsu", vi: "Chào hỏi khi kết thúc onsite" },
    ],
    // phần tra cứu thêm (không theo bài)
    extras: [
      { id: "nhan-vat", ico: "👥", jp: "主な登場人物", vi: "Nhân vật trong sách" },
      { id: "kinh-ngu", ico: "🙇", jp: "敬語のまとめ", vi: "Tóm tắt kính ngữ" },
      { id: "viet-tat", ico: "🔤", jp: "略語一覧", vi: "Từ viết tắt IT" },
      { id: "tu-vung", ico: "🔎", jp: "用語索引", vi: "Tra cứu toàn bộ từ vựng" },
    ],
  },
];

export const bookById = (id) => LIBRARY.find((b) => b.id === id);
export const lessonUrl = (book, n) => `/library/${book}/${n}.json`;
export const lessonName = (B, n) => (B?.lessonLabel ? `${B.lessonLabel}${n}` : `第${n}課`);
